# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b3cc8928d73e6ee9a24fc7b419a2372b65d0816775b59d0c2fc216514915269f83ea07471fa18bac2ff40e98062f9a0e82b3f8aa74cc32e355d9dd1c13bd10

test:
  secret_key_base: 701dd3f834267540faf728d64943025112fca056f516076b715eb1c78bdd35215dc54398de2322bced15188875d6e7559808f614bf420528f1656e085804b42f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
